version: '3.5'
services:
  dst-server:
    image: jamesits/dst-server:latest
    container_name: dst-xuxu
    restart: "on-failure:5"
    environment:
      - DST_CLUSTER_TOKEN=pds-g^KU_OuuPEJ6u^WUaNUYKTGAX+X0JjeJI8BfQSwxjEWFMXrC8N1mGJS4E=
      # - DST_CLUSTER_NAME=Xuxu
    ports:
      - "10999-11000:10999-11000/udp"
      - "12346-12347:12346-12347/udp"
    #      - "10999-11000:10999-11000/udp"
    #      - "12346-12347:12346-12347/udp"
    #      - "11000-11001:11000-11001/udp"
    #      - "27018-27019:27018-27019/udp"
    volumes:
      # - ./data:/data
      # -  ~/.klei/DoNotStarveTogether:/data
      -  ~/.klei:/data
    stop_grace_period: 6m
# networks:
#   default:
#     external:
#       name: darkraise
